name: Deploy to GitHub Pages

# お試し Actions
# github pages にデプロイする。
# ちょっと怖いので feature/actions でお試し。
# 確認できたら master にする。

on:
  push:
    branches:
      - feature/actions
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest master
        uses: actions/checkout@v3
        with:
          ref: feature/actions

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
